[tool.black]
line-length = 79
include = '''
/(
    src
  | tests
)/
'''
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.nox
  | __pycache__
  | \.pyc$
  | \.ipynb$
  | \.md$
  | build
  | venv
  | dist
  | \.eggs
)/
'''

[tool.isort]
profile = "black"
src_paths = [".","src", "tests"]
skip=[".tox",".nox","venv","build","dist","resources","model","log"]
skip_glob=["venv/*","build/*","dist/*","resources/*"]
sections="FUTURE,STDLIB,SETUPTOOLS,TEST,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
known_first_party = "src"

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "node-and-date"
